# For a standard setup with the latest Raytac MDBT50Q-CX Blue dongle (USB C
# connector), you do not need to modify this file. If you are using a different
# dongle (such as one of the older Raytac dongles), you will need to modify
# "board". For a dongleless setup, you will need to modify both "board" and
# "shield". Please see "readme.md" for more details.
include:
  - board: raytac_mdbt50q_cx_blue
    shield: slicemk_ergodox_dongle
