on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-init
        with:
          args: 'init "-l config"'
      - name: West Update
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-update
        with:
          args: 'update'
      - name: West Config Zephyr Base
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-config
        with:
          args: 'config "--global zephyr.base-prefer configfile"'
      - name: West Zephyr Export
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-zephyr-export
        with:
          args: 'zephyr-export'
      - name: West Build (ErgoDox Wireless Dongle)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-slicemk-ergodox-dongle
        with:
          args: 'build "-s zmk/app -b mdbt50q_rx -- -DSHIELD=slicemk_ergodox_dongle -DZMK_CONFIG=/github/workspace/config"'
      - name: DTS File (ErgoDox Wireless Dongle)
        if: ${{ always() }}
        run: cat -n build/zephyr/mdbt50q_rx.dts.pre.tmp
      - name: Kconfig File (ErgoDox Wireless Dongle)
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Archive (ErgoDox Wireless Dongle)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: build/zephyr/zmk.uf2
